// Archived config generated by create-next-app (TS config is unsupported in Next.js 14).
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;
